#!/bin/bash
# Script para configurar variables de entorno en Vercel

echo "Configura estas variables de entorno en Vercel:"
echo ""
echo "1. Ve a: https://vercel.com/dashboard"
echo "2. Selecciona tu proyecto: web-bbrokers"
echo "3. Settings → Environment Variables"
echo ""
echo "Variable 1:"
echo "  Name: NEXTAUTH_SECRET"
echo "  Value: desarrollo-temporal-cambiar-en-produccion-a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
echo "  Environments: Production, Preview, Development"
echo ""
echo "Variable 2:"
echo "  Name: NEXTAUTH_URL"
echo "  Value: https://web-bbrokers.vercel.app"
echo "  Environments: Production"
echo ""
echo "4. Guarda y Redeploy el proyecto"
echo ""
echo "Alternativa - usando Vercel CLI:"
echo "  vercel env add NEXTAUTH_SECRET"
echo "  vercel env add NEXTAUTH_URL"
