"use client";
import Image from "next/image";
import { useMemo, useState, type FormEvent } from "react";
import { ArrowLeft, Check, ChevronDown, ChevronLeft, ChevronRight, Loader2, MapPin } from "lucide-react";
import type { MeetingLink } from "@/lib/meeting-scheduler";
import { argentinaLocalDateTimeToIso } from "@/lib/argentina-time";

const pad=(n:number)=>String(n).padStart(2,"0");
const key=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const months=["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"];
const labels=["LUN.","MAR.","MIÉ.","JUE.","VIE.","SÁB.","DOM."];
const addMinutes=(time:string,minutes:number)=>{const[h,m]=time.split(":").map(Number);const total=h*60+m+minutes;return `${pad(Math.floor(total/60))}:${pad(total%60)}`};

export function PublicMeetingScheduler({link,initialBusy}:{link:MeetingLink;initialBusy:{start:string;end:string}[]}){
 const today=new Date();today.setHours(0,0,0,0);
 const[month,setMonth]=useState(new Date(today.getFullYear(),today.getMonth(),1));
 const[date,setDate]=useState<Date|null>(null),[duration,setDuration]=useState(link.durations[0]),[slot,setSlot]=useState("");
 const[meetingMode,setMeetingMode]=useState<"in_person"|"google_meet">(link.meetingModes[0]||"in_person");
 const[step,setStep]=useState<"time"|"info"|"done">("time"),[form,setForm]=useState({name:"",email:"",phone:"",notes:""});
 const[saving,setSaving]=useState(false),[error,setError]=useState("");
 const days=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1),start=new Date(first);start.setDate(first.getDate()-((first.getDay()+6)%7));return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})},[month]);
 const available=(d:Date)=>d>=today&&d.getMonth()===month.getMonth()&&link.weekdays.includes(d.getDay())&&d<=new Date(Date.now()+45*86400000);
 const slots=useMemo(()=>{if(!date)return[];const values:string[]=[];for(let t=link.startTime;addMinutes(t,duration)<=link.endTime;t=addMinutes(t,link.slotInterval)){const start=new Date(argentinaLocalDateTimeToIso(key(date),t)),end=new Date(start.getTime()+duration*60000);if(start.getTime()>Date.now()&&!initialBusy.some(b=>start<new Date(b.end)&&end>new Date(b.start)))values.push(t)}return values},[date,duration,initialBusy,link]);
 const confirm=async(e:FormEvent)=>{e.preventDefault();if(!date||!slot)return;setSaving(true);setError("");try{const startsAt=argentinaLocalDateTimeToIso(key(date),slot);const r=await fetch(`/api/meetings/${link.slug}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,startsAt,duration,meetingMode})});const data=await r.json();if(!r.ok)throw new Error(data.error);setStep("done")}catch(e){setError(e instanceof Error?e.message:"No se pudo confirmar la reunión.")}finally{setSaving(false)}};
 if(step==="done")return <main className="min-h-screen bg-[#f5f7fa] px-5 py-20 text-[#33475b]"><section className="mx-auto max-w-[620px] bg-white px-10 py-14 text-center shadow-[0_2px_8px_rgba(51,71,91,.16)]"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#dff3ef] text-[#008f9c]"><Check className="h-8 w-8"/></span><h1 className="mt-7 text-[32px] font-semibold">Reunión confirmada</h1><p className="mt-4 text-lg leading-7">La invitación fue enviada a <strong>{form.email}</strong> y quedó agendada en el calendario de {link.agentName}.</p></section></main>;
 return <main className="min-h-screen overflow-x-hidden border-t-[5px] border-[#33475b] bg-[#f5f7fa] pb-12 text-[#33475b]">
  <div className="relative mx-auto h-[108px] w-full max-w-[650px]"><div className="absolute left-1/2 top-0 h-[3px] w-[74%] -translate-x-1/2 bg-[#cbd6df]"/><div className="absolute left-[16%] top-[-15px] h-10 w-10 rounded-full border-[4px] border-[#ff7a59] bg-[#f5f7fa]"/><div className="absolute right-[16%] top-[-15px] h-10 w-10 rounded-full border-[4px] border-[#cbd6df] bg-[#f5f7fa]"/><div className="flex h-full items-center justify-between px-3 pt-5 text-[18px] font-medium sm:text-[21px]"><span>ELIGE UNA HORA</span><span>TU INFORMACIÓN</span></div></div>
  <div className="mb-5 flex justify-center"><Image src="/logo.png" alt="Barrera Brokers" width={76} height={76} className="h-[76px] w-[76px] object-contain" priority/></div>
  <section className="mx-auto grid min-h-[680px] w-[calc(100%-32px)] max-w-[1180px] overflow-hidden rounded-[5px] bg-white shadow-[0_2px_9px_rgba(51,71,91,.17)] lg:grid-cols-2">
   <div className="bg-[#46657f] px-6 py-8 text-white sm:px-10 lg:px-12">
    {step==="info"&&<button onClick={()=>setStep("time")} className="mb-7 inline-flex items-center gap-2 text-base text-white/80"><ArrowLeft className="h-5 w-5"/>Cambiar horario</button>}
    <div className="flex flex-col items-center text-center"><div className="relative h-[76px] w-[76px] overflow-hidden rounded-full bg-white/15">{link.agentPhoto?<Image src={link.agentPhoto} alt={link.agentName} fill className="object-cover"/>:<span className="flex h-full items-center justify-center text-2xl font-semibold">{link.agentName.charAt(0)}</span>}</div><h1 className="mt-3 text-[24px] font-light leading-tight sm:text-[28px]">{link.title}</h1></div>
    {step==="time"&&<><div className="mx-auto mt-4 flex max-w-[390px] items-center justify-between"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} className="text-white/45"><ChevronLeft className="h-6 w-6"/></button><h2 className="text-[22px] font-semibold">{months[month.getMonth()]} {month.getFullYear()}</h2><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight className="h-6 w-6"/></button></div><div className="mt-7 grid grid-cols-7 text-center text-[13px] font-bold sm:text-[14px]">{labels.map(x=><span key={x}>{x}</span>)}</div><div className="mt-3 grid grid-cols-7 gap-y-2 text-center">{days.map(d=>{const enabled=available(d),selected=date&&key(date)===key(d);return <button key={d.toISOString()} disabled={!enabled} onClick={()=>{setDate(d);setSlot("")}} className={`mx-auto h-10 w-10 rounded-full text-[15px] ${selected?"bg-white font-semibold text-[#46657f]":enabled?"text-white hover:bg-white/10":"text-white/28"}`}>{d.getDate()}</button>})}</div></>}
   </div>
   <div className="px-6 py-8 sm:px-10 lg:px-12">{step==="time"?<>
    <h2 className="text-[21px] font-bold">¿Cómo querés reunirte?</h2><div className="mt-3 flex gap-2">{link.meetingModes.map(mode=><button key={mode} onClick={()=>setMeetingMode(mode)} className={`flex-1 rounded-[4px] border px-3 py-3 text-sm font-semibold ${meetingMode===mode?"border-[#0091ae] bg-[#e5f4f6] text-[#007a8a]":"border-[#b8c8d4] bg-white"}`}><span className="flex items-center justify-center gap-2"><MapPin className="h-4 w-4"/>{mode==="google_meet"?"Virtual · Google Meet":"Presencial"}</span>{mode==="in_person"&&<small className="mt-1 block font-normal">{link.location}</small>}</button>)}</div>
    <h2 className="mt-7 text-[21px] font-bold">¿Cuánto tiempo necesitas?</h2><div className="mt-3 flex h-[48px] overflow-hidden rounded-[4px] border border-[#b8c8d4]">{link.durations.map(v=><button key={v} onClick={()=>{setDuration(v);setSlot("")}} className={`flex-1 border-r border-[#b8c8d4] text-[15px] font-medium last:border-r-0 ${duration===v?"bg-[#c7d5e1]":"bg-white"}`}>{v===60?"1 hora":`${v} minutos`}</button>)}</div>
    <h2 className="mt-7 text-[21px] font-bold">¿A qué hora puedes?</h2><p className="mt-1 text-[16px] leading-6">{date?<>Mostrando los horarios para el <strong>{new Intl.DateTimeFormat("es-AR",{day:"numeric",month:"long",year:"numeric"}).format(date)}</strong></>:"Elegí un día disponible en el calendario"}</p><button type="button" className="mt-3 flex w-full items-center justify-between px-2 text-left text-[15px] font-bold text-[#0091ae]"><span>UTC −03:00 Argentina, Brasil</span><ChevronDown className="h-4 w-4 fill-[#0091ae]"/></button>
    <div className="mt-3 max-h-[270px] space-y-2 overflow-y-auto pr-3 [scrollbar-color:#777_transparent]">{slots.map(t=><button key={t} onClick={()=>setSlot(t)} className={`h-[52px] w-full rounded-[4px] border text-[18px] font-medium ${slot===t?"border-[#0091ae] bg-[#e5f4f6] text-[#007a8a]":"border-[#cbd6df] bg-white hover:border-[#0091ae]"}`}>{t}</button>)}{date&&!slots.length&&<p className="py-8 text-center text-sm">No quedan horarios disponibles para este día.</p>}</div>{slot&&<button onClick={()=>setStep("info")} className="mt-3 w-full rounded-[4px] bg-[#ff7a59] px-5 py-3 text-base font-bold text-white">Siguiente</button>}
   </>:<form onSubmit={confirm}><h2 className="text-[29px] font-bold">Tu información</h2><p className="mt-3 text-lg">Completá tus datos para confirmar la reunión.</p><div className="mt-9 space-y-6"><label className="block text-lg font-bold">Nombre y apellido<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-2 w-full rounded-[3px] border border-[#b8c8d4] px-4 py-4 font-normal"/></label><label className="block text-lg font-bold">Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="mt-2 w-full rounded-[3px] border border-[#b8c8d4] px-4 py-4 font-normal"/></label><label className="block text-lg font-bold">Teléfono<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="mt-2 w-full rounded-[3px] border border-[#b8c8d4] px-4 py-4 font-normal"/></label><label className="block text-lg font-bold">Mensaje (opcional)<textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="mt-2 w-full resize-none rounded-[3px] border border-[#b8c8d4] px-4 py-4 font-normal"/></label></div>{error&&<p className="mt-5 text-base font-semibold text-red-700">{error}</p>}<button disabled={saving} className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-[4px] bg-[#ff7a59] px-6 py-4 text-lg font-bold text-white">{saving&&<Loader2 className="h-5 w-5 animate-spin"/>}Confirmar reunión</button></form>}</div>
  </section>
 </main>;
}
