const HIDDEN_HUBSPOT_CONTACT_FIELDS = new Set([
  "firstname",
  "lastname",
  "email",
  "phone",
  "mobilephone",
  "num_notes",
  "hs_pipeline",
  "hs_object_id",
  "hs_email_type",
  "hs_is_contact",
  "hs_is_enriched",
  "hs_is_unworked",
  "hs_lead_status",
  "lifecyclestage",
  "hs_email_domain",
  "hs_all_owner_ids",
  "hs_latest_source",
  "hs_object_source",
  "hubspot_owner_id",
  "lastmodifieddate",
  "hs_count_is_worked",
  "hs_count_is_unworked",
  "hs_marketable_status",
  "hs_marketable_reason_type",
  "hs_registered_member",
  "hs_user_ids_of_all_owners",
  "hubspot_owner_assigneddate",
  "hs_last_sales_activity_date",
  "hs_marketable_until_renewal",
  "hs_sa_first_engagement_date",
  "hs_time_to_first_engagement",
  "hs_v2_time_in_current_stage",
  "hs_num_associated_open_deals",
  "hs_sa_first_engagement_descr",
  "num_unique_conversion_events",
  "hs_associated_target_accounts",
  "hs_first_engagement_object_id",
  "hs_messaging_engagement_score",
  "hs_calculated_form_submissions",
  "hs_calculated_phone_number",
  "hs_calculated_phone_number_country_code",
  "hs_currently_enrolled_in_prospecting_agent",
  "hs_membership_has_accessed_private_content",
  "hs_prospecting_agent_actively_enrolled_count",
  "hs_prospecting_agent_total_enrolled_count",
  "hs_sa_first_engagement_object_type",
  "hs_searchable_calculated_international_phone_number",
  "hs_searchable_calculated_phone_number",
  "hs_sequences_actively_enrolled_count",
  "hs_user_ids_of_all_notification_recipients",
  "hs_whatsapp_phone_number",
  "notes_last_updated",
  "notes_last_contacted",
  "first_conversion_date",
  "first_conversion_event_name",
  "recent_conversion_date",
  "recent_conversion_event_name",
  "hs_analytics_last_url",
  "hs_analytics_first_url",
  "hs_updated_by_user_id",
  "hs_facebook_ad_clicked",
  "hs_first_outreach_date",
  "hs_notes_last_activity",
  "hs_object_source_label",
  "hs_analytics_num_visits",
  "hs_latest_source_data_1",
  "hs_latest_source_data_2",
  "hs_marketable_reason_id",
  "hs_num_active_contracts",
  "hs_v2_date_entered_lead",
  "hs_social_twitter_clicks",
  "num_conversion_events",
  "hs_all_contact_vids",
  "hs_analytics_source",
  "hs_object_source_id",
  "num_contacted_notes",
  "hs_analytics_revenue",
]);

export function shouldShowHubSpotContactField(key: string) {
  if (HIDDEN_HUBSPOT_CONTACT_FIELDS.has(key)) return false;
  if (key.startsWith("hs_analytics_")) return false;
  if (key.startsWith("hs_latest_source_")) return false;
  if (key.startsWith("hs_marketable_")) return false;
  if (key.startsWith("hs_membership_")) return false;
  if (key.startsWith("hs_prospecting_agent_")) return false;
  if (key.startsWith("hs_sa_")) return false;
  if (key.startsWith("hs_sequences_")) return false;
  if (key.startsWith("hs_social_")) return false;
  if (key.startsWith("hs_v2_date_")) return false;
  if (key.startsWith("hs_v2_time_")) return false;
  return true;
}
