// Logical specialists share one validated response to avoid six model calls per event.
// Future specialists can add instructions without coupling to UI, storage or delivery.
export const salesAgents = [
  { id: 'lead_analyst', instruction: 'La ficha del contacto (lead.notes, forms, imported y development) es la fuente de lo que busca. Usá esos datos para personalizar la acción, no para repetir un interrogatorio. El objetivo del informe es decidir qué debe hacer el agente con este cliente a partir de la interacción. No deduzcas nacionalidad por el nombre.' },
  { id: 'conversation_analyst', instruction: 'Interpretá la cronología y el contexto de mensajes, notas, llamadas y resultados. summary debe resumir la interacción: qué hizo el agente, qué respondió el cliente, quién debe actuar y qué frena el avance, no repetir la ficha inmobiliaria. Detectá objeciones, intención y cambios respecto del resumen previo; explicá la evidencia del cambio. Si falta historial, declaralo sin inventar una conversación. No confundas una tarea programada con una llamada realizada.' },
  { id: 'followup_manager', instruction: 'Diferenciá quién espera respuesta. Ajustá followupHours a intención, etapa, urgencia y compromisos del cliente; no propongas insistir si pidió no ser contactado.' },
  { id: 'sales_coach', instruction: 'Elegí una próxima acción ejecutable: responder por WhatsApp, enviar correo, realizar llamada o esperar hasta el compromiso acordado. Indicá canal, objetivo, momento y motivo basado en la última interacción. suggestedMessage debe contener el texto listo para revisar y usar en ese canal, con un único llamado a la acción concreto (responder una pregunta, elegir horario o coordinar visita). Para correo incluí asunto y cuerpo; para WhatsApp texto breve; para llamada un guion breve y una pregunta de cierre. No incluyas instrucciones al agente dentro del texto que enviaría al cliente. Si callHistory.count es cero y lead.hasPhone es true, priorizá proponer una primera llamada registrada, salvo que haya un mensaje pendiente que responder, un compromiso futuro, un pedido de no contacto o una preferencia contraria del cliente. Si hay llamadas, evaluá el último resultado antes de insistir. Nunca afirmes que no se llamó: decí que no hay llamadas registradas. No inventes disponibilidad ni horarios confirmados.' },
  { id: 'pipeline_monitor', instruction: 'Detectá reservas detenidas, propuestas sin seguimiento, visitas con resultado registrado y oportunidades para avanzar. Sugerí cambios de etapa pero nunca los ejecutes.' },
  { id: 'data_completion', instruction: 'Antes de declarar un dato faltante, revisá toda la ficha, formularios, importaciones, notas y resumen previo. No vuelvas a preguntar presupuesto, zona, ambientes o forma de pago si ya figuran. Solo proponé una pregunta si falta un dato imprescindible para el próximo paso; si hay contradicción, pedí confirmar esa diferencia. No conviertas el informe en una lista de datos por completar. Compará solo con inventario documentado.' },
] as const;

export const specialistInstructions = salesAgents.map(a => `${a.id}: ${a.instruction}`).join('\n');
