"use client";
import { useCallback,useEffect,useRef,useState } from 'react';
import Link from 'next/link';
import type { Analysis } from '@/lib/ai-sales/model';

type Lead={id:string;created_at:string;analysis_state:'processing'|'failed'|'retry'|'pending'|'updated';manual_pending:boolean;retry_at:string|null;attempts:number;first_name:string;last_name:string;source:string;pipeline:string;agent:string;development:string;ai_score:number|null;ai_status:string;last_analyzed_at:string|null;last_error:string|null;next_followup_at:string|null;analysis:{semantic?:Analysis;priority?:string;nextAction?:string;waiting?:boolean;risk?:boolean;reactivate?:boolean;visitFollowup?:boolean;closed?:boolean;dimensions?:Record<string,number|null>}};
type Rec={id:string;lead_id:string;title:string;reasoning:string;suggested_message:string;priority:string;confidence:number;due_at:string};
type Feed={id:string;lead_id:string;first_name:string;previous_score:number|null;score:number;reasoning:string;created_at:string};
type Data={ready:boolean;enabled:boolean;pending:number;total:number;counts:Record<string,number>;owners:string[];leads:Lead[];recommendations:Rec[];feed:Feed[];team:{id:string;name:string;leads:number;hot:number;waiting:number;overdue:number;no_activity:number;visited:number;active:number}[]};
const button='min-h-10 rounded-md border border-ink/20 px-3 py-2 text-sm font-medium hover:bg-cream-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#006b6b] disabled:opacity-50';
const date=(value:string)=>new Date(value).toLocaleString('es-AR',{timeZone:'America/Argentina/Buenos_Aires',dateStyle:'short',timeStyle:'short'});
const categories=[['all','Qué hacer ahora'],['hot','Alta prioridad'],['waiting','Esperando respuesta'],['followup','Seguimientos vencidos'],['visit','Visitas sin seguimiento'],['risk','En riesgo'],['reactivate','Reactivar'],['advancing','Avanzando']] as const;
const aiStatuses=['NEW','QUALIFYING','ACTIVE','HIGH_INTENT','VISIT_READY','NEGOTIATING','WAITING_CLIENT','WAITING_AGENT','FOLLOW_UP_REQUIRED','COLD','REACTIVATION'];
function priorityBadge(lead:Lead){
 if(!lead.last_analyzed_at||lead.ai_score===null)return {label:'Pendiente de análisis',style:'bg-slate-100 text-slate-700'};
 if(['CLOSED_WON','LOST'].includes(lead.ai_status))return {label:'Cerrado',style:'bg-slate-100 text-slate-700'};
 if(lead.ai_score>=80)return {label:'Muy alta',style:'bg-red-100 text-red-900'};
 if(lead.ai_score>=60)return {label:'Alta',style:'bg-orange-100 text-orange-900'};
 if(lead.ai_score>=40)return {label:'Media',style:'bg-amber-100 text-amber-900'};
 if(lead.ai_score>=20)return {label:'Baja',style:'bg-blue-100 text-blue-900'};
 return {label:'Muy baja',style:'bg-slate-100 text-slate-700'};
}
export function AiSales({leadId,expandDetails=false,embedded=false}:{leadId?:string;expandDetails?:boolean;embedded?:boolean}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[minScore,setMinScore]=useState(''),[owner,setOwner]=useState(''),[status,setStatus]=useState('');
 const [advanced,setAdvanced]=useState<Record<string,string>>({}),[page,setPage]=useState(0),[loading,setLoading]=useState(false);
 const requestSeq=useRef(0);
 const invalidate=useCallback(()=>{requestSeq.current++;},[]);
 const [drafts,setDrafts]=useState<Record<string,string>>({});
 const params=new URLSearchParams(leadId?{leadId}:{category:filter,query,score:minScore||'0',owner,status,page:String(page),...advanced}).toString();
 const load=useCallback(async()=>{const seq=++requestSeq.current;setLoading(true);try{const response=await fetch(`/api/crm/ai-sales?${params}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw Error(body.error);if(seq===requestSeq.current){setData(body);setError('');}}catch{if(seq===requestSeq.current)setError('No se pudo consultar el copiloto. Reintentá en unos momentos.');}finally{if(seq===requestSeq.current)setLoading(false);}},[params]);
 useEffect(()=>{setPage(0);},[filter,query,minScore,owner,status,advanced]);
 useEffect(()=>{const debounce=setTimeout(()=>void load(),300);const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},leadId?10000:60000);return()=>{clearTimeout(debounce);clearInterval(timer);invalidate();};},[load,invalidate,leadId]);
 async function action(id:string,action:string,recommendationId?:string){setBusy(true);setNotice('');try{const r=await fetch('/api/crm/ai-sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({leadId:id,action,recommendationId})});if(!r.ok)throw Error();setNotice(action==='reanalyze'?'Solicitud guardada. El estado del informe indica el avance.':'Acción guardada.');await load();}catch{setError('No se guardó la acción. Reintentá.');}finally{setBusy(false);}}
 const visible=data?.leads||[];
 return <section id={embedded?undefined:"ai-sales"} className="rounded-xl bg-white p-5 text-ink ring-1 ring-ink/10">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">{leadId?'AI Sales Copilot':'AI Sales · Qué hacer ahora'}</h2><p className="mt-2 max-w-[70ch] text-sm text-ink/75">Prioridades basadas en los registros del CRM. Las inferencias requieren revisión del agente.</p></div><button className={button} onClick={()=>void load()}>Recargar informe</button></div>
  {error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="mt-3 text-sm text-[#006b6b]">{notice}</p>}
  {!data&&!error&&<p className="py-5" role="status">Consultando análisis guardados…</p>}
  {data&&!data.ready&&<p className="py-5">El copiloto está pendiente de activación en el servidor.</p>}
  {data?.ready&&<>
   {!data.enabled&&<p role="status" className="mt-3 rounded-md bg-amber-50 p-3 text-sm text-amber-900">El análisis automático está desactivado en este servidor. Los datos guardados siguen disponibles.</p>}
   {!leadId&&<><p className="mt-3 text-sm text-ink/75">{data.pending} contactos pendientes de análisis · {data.total} resultados. Los filtros consultan toda tu cartera autorizada.</p>
    <nav aria-label="Prioridades comerciales" className="my-4 flex flex-wrap gap-2">{categories.map(([value,label])=><button key={value} onClick={()=>setFilter(value)} aria-pressed={filter===value} className={`${button} ${filter===value?'bg-[#006b6b] text-white hover:bg-[#005858]':''}`}>{label} · {data.counts?.[value]||0}</button>)}</nav>
    <div className="mb-4 flex flex-wrap gap-3"><label className="text-sm">Buscar<input className="ml-2 rounded-md border border-ink/30 p-2" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nombre, zona, presupuesto…"/></label><label className="text-sm">Score mínimo<input type="number" min="0" max="100" className="ml-2 w-20 rounded-md border border-ink/30 p-2" value={minScore} onChange={e=>setMinScore(e.target.value)}/></label><label className="text-sm">Agente<select value={owner} onChange={e=>setOwner(e.target.value)} className="ml-2 rounded-md border border-ink/30 p-2"><option value="">Todos los visibles</option>{data.owners.map(a=><option key={a}>{a}</option>)}</select></label><label className="text-sm">Estado AI<select value={status} onChange={e=>setStatus(e.target.value)} className="ml-2 rounded-md border border-ink/30 p-2"><option value="">Todos</option>{aiStatuses.map(s=><option key={s}>{s}</option>)}</select></label></div>
    <details className="mb-4 text-sm"><summary className="cursor-pointer font-medium">Más filtros comerciales</summary><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['intent','Intención mínima','number'],['urgency','Urgencia mínima','number'],['source','Fuente','text'],['campaign','Campaña (formulario)','text'],['development','Desarrollo','text'],['zone','Zona','text'],['budget','Presupuesto (texto)','text'],['country','País','text'],['language','Idioma','text'],['lastBefore','Último contacto anterior a','date'],['followupBefore','Seguimiento hasta','date']].map(([key,label,type])=><label key={key}>{label}<input type={type} min={type==='number'?0:undefined} max={type==='number'?100:undefined} className="mt-1 block w-full rounded-md border border-ink/30 p-2" value={advanced[key]||''} onChange={e=>setAdvanced(v=>({...v,[key]:e.target.value}))}/></label>)}</div></details></>}
   {loading&&<p role="status" className="text-sm text-ink/75">Actualizando resultados…</p>}
   {!visible.length&&<p className="py-5">No hay contactos para estos filtros.</p>}
   {!leadId&&<p className="mb-3 text-sm text-ink/75">Mayor score primero; sin análisis, al final. En empates: Interesado → En curso → Contactado → otros estados, y luego los más recientes. Abrí Detalles para ver el análisis completo.</p>}
   <div className="divide-y divide-ink/15">{visible.map(l=>{const a=l.analysis?.semantic;const priority=priorityBadge(l);return <article key={l.id} className="py-4">
    <div className="flex flex-wrap items-center justify-between gap-2"><Link href={`/admin/crm/${l.id}#ai-sales`} className="min-w-0 break-words text-base font-semibold text-[#006b6b] hover:underline">{l.first_name} {l.last_name}</Link><span className={`rounded-md px-2.5 py-1 text-xs font-semibold ${priority.style}`}>{l.last_analyzed_at&&l.ai_score!==null?`${l.ai_score}/100 · `:''}{priority.label}</span></div>
    <p className="mt-1 text-sm text-ink/75">{l.agent||'Sin asignar'} · {l.pipeline}{l.created_at&&<> · Alta: {date(l.created_at)}</>}</p>
    <details open={expandDetails || undefined} className="group mt-2 text-sm"><summary className="w-fit cursor-pointer rounded-md py-2 font-medium text-[#006b6b] hover:underline focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#006b6b]">Detalles<span className="sr-only"> de {l.first_name} {l.last_name}</span></summary>
    <div className="mt-2 min-w-0 break-words">
    <p role="status" className="mb-3 text-sm font-medium text-[#006b6b]">{l.analysis_state==='processing'?'Analizando la interacción…':l.analysis_state==='failed'?'Análisis detenido tras varios intentos. Podés volver a solicitarlo.':l.analysis_state==='retry'?`Reintento pendiente${l.retry_at?` desde ${date(l.retry_at)}`:''}. Se conserva el informe anterior.`:l.analysis_state==='pending'?'Pendiente de análisis · se procesará automáticamente según la cola y disponibilidad del proveedor.':'Informe actualizado con las interacciones registradas.'}</p>
    <p className="text-sm text-ink/75">Fuente: {l.source||'Sin datos'} · Desarrollo: {l.development||'Sin datos'}{l.ai_status&&` · Estado AI: ${l.ai_status}`}</p>
    {l.last_error&&<p role="status" className="mt-2 text-sm text-red-700">{l.last_error}</p>}
    <p className="mt-3 font-medium">{l.analysis?.nextAction||'Se analizará el contexto comercial en segundo plano.'}</p>
    {l.next_followup_at&&<p className="mt-1 text-sm">Seguimiento recomendado: {date(l.next_followup_at)}</p>}
    {a&&<><p className="mt-3 max-w-[70ch] text-sm leading-relaxed">{a.summary}</p><ul className="mt-2 list-disc space-y-1 pl-5 text-sm">{a.reasoning.slice(0,3).map((r,i)=><li key={i}>{r}</li>)}</ul>
    <div className="mt-3 text-sm"><h3 className="font-medium">Evidencia, información faltante y score</h3><p className="mt-3">Confianza del análisis: {Math.round(a.confidence*100)} %</p><dl className="my-3 grid grid-cols-2 gap-2">{Object.entries(l.analysis.dimensions||{}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value===null?'Sin datos':`${value}/100`}</dd></div>)}</dl><p className="font-medium">Datos confirmados</p><ul>{a.confirmed.map((f,i)=><li key={i}>{f.fact} <span className="text-ink/70">(registro {f.evidenceId})</span></li>)}</ul><p className="mt-3 font-medium">Inferencias de IA</p><ul>{a.inferences.map((v,i)=><li key={i}>{v}</li>)}</ul><p className="mt-3 font-medium">Información faltante</p><ul>{a.missingInformation.map((v,i)=><li key={i}>{v}</li>)}</ul><p className="mt-3 font-medium">Preguntas sugeridas</p><ul>{a.questions.map((v,i)=><li key={i}>{v}</li>)}</ul>{a.propertyMatches.length>0&&<><p className="mt-3 font-medium">Desarrollos para evaluar</p><ul>{a.propertyMatches.map(p=><li key={p.id}>{p.reason}</li>)}</ul></>}</div></>}
    {data.recommendations.filter(r=>r.lead_id===l.id).map(r=><div key={r.id} className="mt-4"><p className="text-sm font-medium">{r.priority} · {r.title}</p>{leadId&&<><label className="mt-3 block text-sm font-medium" htmlFor={`draft-${r.id}`}>Sugerencia de mensaje · revisá y editá antes de enviar</label><textarea id={`draft-${r.id}`} rows={4} className="mt-2 w-full rounded-md border border-ink/30 p-3 text-sm" value={drafts[r.id]??r.suggested_message} onChange={e=>setDrafts(v=>({...v,[r.id]:e.target.value}))}/><div className="mt-2 flex flex-wrap gap-2"><button className={button} onClick={()=>void navigator.clipboard.writeText(drafts[r.id]??r.suggested_message).then(()=>setNotice('Mensaje copiado.')).catch(()=>setError('Seleccioná el texto para copiarlo.'))}>Copiar mensaje</button><button className={button} onClick={()=>window.dispatchEvent(new CustomEvent('crm:ai-email-draft',{detail:{leadId:l.id,text:drafts[r.id]??r.suggested_message}}))}>Revisar y enviar por correo</button></div></>}
    <div className="mt-3 flex flex-wrap gap-2">{[['useful','Útil'],['not_useful','No útil'],['completed','Completar recomendación'],['dismissed','Descartar'],['snoozed','Posponer 24 h']].map(([value,label])=><button key={value} disabled={busy} className={button} onClick={()=>void action(l.id,value,r.id)}>{label}</button>)}</div></div>)}
    {<button disabled={busy||l.analysis_state==='processing'||(l.manual_pending&&l.analysis_state!=='failed')} onClick={()=>void action(l.id,'reanalyze')} className={`${button} mt-4`}>Actualizar análisis</button>}
    {l.last_analyzed_at&&<p className="mt-3 text-xs text-ink/75">Último análisis: {date(l.last_analyzed_at)}</p>}
    </div></details>
   </article>;})}</div>
   {!leadId&&<div className="mt-4 flex items-center gap-3"><button className={button} disabled={page===0||loading} onClick={()=>setPage(v=>v-1)}>Anterior</button><span className="text-sm">Página {page+1} de {Math.max(1,Math.ceil(data.total/50))}</span><button className={button} disabled={(page+1)*50>=data.total||loading} onClick={()=>setPage(v=>v+1)}>Siguiente</button></div>}
   {data.team.length>0&&!leadId&&<details className="mt-6 border-t border-ink/15 pt-4"><summary className="cursor-pointer font-semibold">AI Team Monitor</summary><p className="mt-2 text-sm">Visitas y oportunidades corresponden a contactos analizados. Sin actividad significa que no hay contacto registrado; no evalúa el desempeño del agente.</p><div className="overflow-x-auto"><table className="mt-4 w-full text-left text-sm"><thead><tr>{['Agente','Leads','Alta prioridad','Esperando respuesta','Vencidos','Sin contacto registrado','Con visita realizada','Oportunidades activas'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{data.team.map(a=><tr key={a.id} className="border-t border-ink/10"><td className="p-2">{a.name}</td>{[a.leads,a.hot,a.waiting,a.overdue,a.no_activity,a.visited,a.active].map((v,i)=><td className="p-2" key={i}>{v}</td>)}</tr>)}</tbody></table></div></details>}
   <details className="mt-6 border-t border-ink/15 pt-4"><summary className="cursor-pointer font-semibold">Evolución e historial AI</summary><ol className="mt-3 divide-y divide-ink/10">{data.feed.map(e=><li key={e.id} className="py-3 text-sm"><Link className="font-medium text-[#006b6b]" href={`/admin/crm/${e.lead_id}#ai-sales`}>{e.first_name}</Link> · {e.previous_score??'Inicial'} → {e.score}<p className="mt-1">{e.reasoning}</p><time className="text-xs text-ink/75">{date(e.created_at)}</time></li>)}</ol></details>
  </>}
 </section>;
}
