"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, Check, Clock3, Copy, Loader2, Mail, MessageCircle, NotebookPen, Pencil, Phone, PhoneOff, X } from "lucide-react";

type HeaderLead = { id: string; firstName: string; lastName: string; email: string; countryCode: string; phone: string };
type CallSession = { startedAt: string; endedAt: string; note: string };
function initials(firstName: string, lastName: string) { return `${firstName[0] || ""}${lastName[0] || ""}`.toUpperCase() || "CL"; }
function formatDateTime(value: string) { return new Intl.DateTimeFormat("es-AR", { dateStyle: "medium", timeStyle: "medium" }).format(new Date(value)); }
function formatDuration(startedAt: string, endedAt: string) { const seconds = Math.max(0, Math.round((new Date(endedAt).getTime() - new Date(startedAt).getTime()) / 1000)); const minutes = Math.floor(seconds / 60); const remainder = seconds % 60; return `${minutes} min ${remainder} s`; }

export function CrmContactHeader({ lead, whatsappUrl }: { lead: HeaderLead; whatsappUrl: string }) {
  const router = useRouter();
  const [editingName, setEditingName] = useState(false), [editingEmail, setEditingEmail] = useState(false);
  const [firstName, setFirstName] = useState(lead.firstName), [lastName, setLastName] = useState(lead.lastName), [email, setEmail] = useState(lead.email);
  const [saving, setSaving] = useState(false), [copied, setCopied] = useState(false), [noteOpen, setNoteOpen] = useState(false), [note, setNote] = useState(""), [noteSaving, setNoteSaving] = useState(false), [error, setError] = useState("");
  const [callSession, setCallSession] = useState<CallSession | null>(null), [callSaving, setCallSaving] = useState(false), [callError, setCallError] = useState("");
  const callStorageKey = `barrera-crm-call-${lead.id}`;
  const patchLead = async (payload: Record<string, string>) => { setSaving(true); setError(""); try { const response = await fetch("/api/crm/leads", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: lead.id, ...payload }) }); const data = await response.json().catch(() => null) as { error?: string } | null; if (!response.ok) throw new Error(data?.error || "No se pudo guardar el cambio."); setEditingName(false); setEditingEmail(false); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo guardar el cambio."); } finally { setSaving(false); } };
  const copyEmail = async () => { await navigator.clipboard.writeText(email); setCopied(true); window.setTimeout(() => setCopied(false), 1600); };
  const saveNote = async () => { if (!note.trim()) return; setNoteSaving(true); setError(""); try { const response = await fetch("/api/crm/activities", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leadId: lead.id, type: "nota", title: `Nota sobre ${firstName} ${lastName}`.trim(), body: note.trim() }) }); const data = await response.json().catch(() => null) as { error?: string } | null; if (!response.ok) throw new Error(data?.error || "No se pudo guardar la nota."); setNote(""); setNoteOpen(false); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo guardar la nota."); } finally { setNoteSaving(false); } };
  const updateCallSession = (session: CallSession | null) => { setCallSession(session); if (session) window.localStorage.setItem(callStorageKey, JSON.stringify(session)); else window.localStorage.removeItem(callStorageKey); };
  const finishCall = () => { setCallSession((current) => { if (!current || current.endedAt) return current; const next = { ...current, endedAt: new Date().toISOString() }; window.localStorage.setItem(callStorageKey, JSON.stringify(next)); return next; }); };
  const startCall = () => { const session = { startedAt: new Date().toISOString(), endedAt: "", note: "" }; updateCallSession(session); setCallError(""); window.sessionStorage.removeItem(`${callStorageKey}-hidden`); window.location.href = `tel:${lead.countryCode}${lead.phone}`; };
  const saveCall = async () => { if (!callSession) return; const endedAt = callSession.endedAt || new Date().toISOString(); setCallSaving(true); setCallError(""); try { const body = [`Fecha: ${formatDateTime(callSession.startedAt)}`, `Inicio: ${formatDateTime(callSession.startedAt)}`, `Finalización: ${formatDateTime(endedAt)}`, `Duración: ${formatDuration(callSession.startedAt, endedAt)}`, callSession.note.trim() ? `Nota: ${callSession.note.trim()}` : "Nota: Sin observaciones"].join("\n"); const response = await fetch("/api/crm/activities", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leadId: lead.id, type: "llamada", title: `Llamada con ${firstName} ${lastName}`.trim(), body, scheduledAt: callSession.startedAt }) }); const data = await response.json().catch(() => null) as { error?: string } | null; if (!response.ok) throw new Error(data?.error || "No se pudo registrar la llamada."); updateCallSession(null); router.refresh(); } catch (cause) { setCallError(cause instanceof Error ? cause.message : "No se pudo registrar la llamada."); } finally { setCallSaving(false); } };
  useEffect(() => { try { const saved = window.localStorage.getItem(callStorageKey); if (saved) setCallSession(JSON.parse(saved) as CallSession); } catch { window.localStorage.removeItem(callStorageKey); } }, [callStorageKey]);
  useEffect(() => { const handleStartCall = () => { const session = { startedAt: new Date().toISOString(), endedAt: "", note: "" }; setCallSession(session); window.localStorage.setItem(callStorageKey, JSON.stringify(session)); setCallError(""); window.sessionStorage.removeItem(`${callStorageKey}-hidden`); window.location.href = `tel:${lead.countryCode}${lead.phone}`; }; window.addEventListener("crm:start-call", handleStartCall); return () => window.removeEventListener("crm:start-call", handleStartCall); }, [callStorageKey, lead.countryCode, lead.phone]);
  useEffect(() => { const handleVisibility = () => { if (document.visibilityState === "hidden" && callSession && !callSession.endedAt) window.sessionStorage.setItem(`${callStorageKey}-hidden`, "1"); if (document.visibilityState === "visible" && callSession && !callSession.endedAt && window.sessionStorage.getItem(`${callStorageKey}-hidden`) === "1") { window.sessionStorage.removeItem(`${callStorageKey}-hidden`); setCallSession((current) => { if (!current || current.endedAt) return current; const next = { ...current, endedAt: new Date().toISOString() }; window.localStorage.setItem(callStorageKey, JSON.stringify(next)); return next; }); window.scrollTo({ top: 0, behavior: "smooth" }); } }; document.addEventListener("visibilitychange", handleVisibility); return () => document.removeEventListener("visibilitychange", handleVisibility); }, [callSession, callStorageKey]);
  const actionClass = "inline-flex min-h-11 items-center gap-2 rounded-full border border-ink/14 bg-white px-3 text-xs font-medium text-ink transition-colors hover:border-[#006b6b]/35 hover:bg-[#e7f4f2] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#006b6b]";

  return <>
    <div className="mt-5 flex items-center gap-3"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-[#006b6b] text-base font-semibold text-white">{initials(firstName, lastName)}</span><div className="min-w-0 flex-1">
      {editingName ? <div className="grid gap-2"><input autoFocus value={firstName} onChange={(event) => setFirstName(event.target.value)} aria-label="Nombre" className="h-10 min-w-0 rounded-lg border border-[#006b6b] px-3 text-sm font-medium outline-none ring-2 ring-[#006b6b]/10" /><input value={lastName} onChange={(event) => setLastName(event.target.value)} aria-label="Apellido" className="h-10 min-w-0 rounded-lg border border-[#006b6b] px-3 text-sm font-medium outline-none ring-2 ring-[#006b6b]/10" /><div className="flex gap-2"><button type="button" disabled={saving || !firstName.trim() || !lastName.trim()} onClick={() => void patchLead({ firstName, lastName })} className="inline-flex min-h-9 items-center gap-1 rounded-lg bg-[#006b6b] px-3 text-xs font-semibold text-white disabled:opacity-50">{saving ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Check className="h-3.5 w-3.5" />}Guardar</button><button type="button" onClick={() => { setEditingName(false); setFirstName(lead.firstName); setLastName(lead.lastName); }} className="min-h-9 rounded-lg px-3 text-xs font-medium text-ink/65 hover:bg-[#f3f4f4]">Cancelar</button></div></div> : <div className="flex min-w-0 items-center gap-1"><h1 className="truncate text-xl font-semibold tracking-tight text-ink">{firstName} {lastName}</h1><button type="button" onClick={() => setEditingName(true)} aria-label="Editar nombre" title="Editar nombre" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg text-ink/48 hover:bg-[#e7f4f2] hover:text-[#006b6b]"><Pencil className="h-4 w-4" /></button></div>}
      {!editingName && (editingEmail ? <div className="mt-1 flex min-w-0 gap-2"><input autoFocus type="email" value={email} onChange={(event) => setEmail(event.target.value)} aria-label="Email" className="h-10 min-w-0 flex-1 rounded-lg border border-[#006b6b] px-3 text-sm outline-none ring-2 ring-[#006b6b]/10" /><button type="button" disabled={saving || !email.includes("@")} onClick={() => void patchLead({ email })} aria-label="Guardar email" className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[#006b6b] text-white disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}</button><button type="button" onClick={() => { setEditingEmail(false); setEmail(lead.email); }} aria-label="Cancelar edición" className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg text-ink/55 hover:bg-[#f3f4f4]"><X className="h-4 w-4" /></button></div> : <div className="mt-1 flex min-w-0 items-center gap-1"><button type="button" onClick={() => setEditingEmail(true)} className="min-w-0 break-all text-left text-sm font-medium text-[#006b6b] hover:underline">{email}</button><button type="button" onClick={() => void copyEmail()} aria-label="Copiar email" title="Copiar email" className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-ink/45 hover:bg-[#e7f4f2] hover:text-[#006b6b]">{copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}</button></div>)}
    </div></div>{error && <p role="alert" className="mt-3 text-xs font-medium text-red-700">{error}</p>}
    <div className="mt-5 flex flex-wrap gap-2 border-t border-ink/10 pt-4"><button type="button" onClick={() => window.dispatchEvent(new Event("crm:open-email-composer"))} className={actionClass}><Mail className="h-4 w-4" />Correo</button><button type="button" onClick={callSession && !callSession.endedAt ? finishCall : startCall} className={actionClass}>{callSession && !callSession.endedAt ? <PhoneOff className="h-4 w-4" /> : <Phone className="h-4 w-4" />}{callSession && !callSession.endedAt ? "Finalizar llamada" : "Llamar"}</button>{whatsappUrl && <a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className={actionClass}><MessageCircle className="h-4 w-4" />WhatsApp</a>}<button type="button" onClick={() => window.dispatchEvent(new Event("crm:open-meeting-scheduler"))} className={actionClass}><CalendarDays className="h-4 w-4" />Reunión</button><button type="button" onClick={() => { setError(""); setNoteOpen(true); }} className={actionClass}><NotebookPen className="h-4 w-4" />Nota</button></div>
    {callSession && <section aria-live="polite" className="mt-4 rounded-xl border border-[#006b6b]/20 bg-[#f2f8f7] p-4"><div className="flex items-start gap-3"><span className={`mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-full ${callSession.endedAt ? "bg-[#006b6b] text-white" : "bg-emerald-100 text-emerald-700"}`}>{callSession.endedAt ? <PhoneOff className="h-4 w-4" /> : <Phone className="h-4 w-4" />}</span><div className="min-w-0 flex-1"><h2 className="text-sm font-semibold text-ink">{callSession.endedAt ? "Llamada finalizada" : "Llamada en curso"}</h2><div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-xs text-ink/65"><span>Inicio: {formatDateTime(callSession.startedAt)}</span>{callSession.endedAt && <><span>Fin: {formatDateTime(callSession.endedAt)}</span><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" />{formatDuration(callSession.startedAt, callSession.endedAt)}</span></>}</div></div></div>{callSession.endedAt ? <><label className="mt-4 block text-sm font-semibold text-ink">Nota de la llamada<textarea autoFocus value={callSession.note} onChange={(event) => updateCallSession({ ...callSession, note: event.target.value })} rows={4} placeholder="Resultado de la conversación, interés y próximo paso…" className="mt-2 w-full resize-y rounded-lg border border-ink/15 bg-white px-3 py-3 font-normal leading-relaxed outline-none placeholder:text-ink/48 focus:border-[#006b6b] focus:ring-2 focus:ring-[#006b6b]/15" /></label>{callError && <p role="alert" className="mt-3 text-sm font-medium text-red-700">{callError}</p>}<div className="mt-4 flex flex-wrap justify-end gap-2"><button type="button" onClick={() => updateCallSession(null)} disabled={callSaving} className="min-h-11 rounded-lg border border-ink/15 bg-white px-4 text-sm font-medium text-ink disabled:opacity-50">Descartar</button><button type="button" onClick={() => void saveCall()} disabled={callSaving} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#006b6b] px-5 text-sm font-semibold text-white disabled:opacity-50">{callSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}Guardar llamada</button></div></> : <div className="mt-4 flex justify-end"><button type="button" onClick={finishCall} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#006b6b] px-5 text-sm font-semibold text-white"><PhoneOff className="h-4 w-4" />Finalizar y agregar nota</button></div>}</section>}
    {noteOpen && <div className="fixed inset-0 z-50 flex items-end justify-center bg-ink/45 sm:items-center sm:p-5" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setNoteOpen(false); }}><section role="dialog" aria-modal="true" aria-labelledby="note-dialog-title" className="w-full max-w-lg rounded-t-xl bg-white p-5 sm:rounded-xl sm:p-6"><div className="flex items-start justify-between"><div><h2 id="note-dialog-title" className="text-lg font-semibold text-ink">Agregar nota</h2><p className="mt-1 text-sm text-ink/60">Se guardará en las actividades de {firstName}.</p></div><button type="button" onClick={() => setNoteOpen(false)} aria-label="Cerrar" className="flex h-10 w-10 items-center justify-center rounded-lg hover:bg-[#e7f4f2]"><X className="h-5 w-5" /></button></div><label className="mt-5 block text-sm font-semibold text-ink">Nota<textarea autoFocus value={note} onChange={(event) => setNote(event.target.value)} rows={6} placeholder="Escribí el seguimiento, una observación o el próximo paso…" className="mt-2 w-full resize-y rounded-lg border border-ink/15 px-3 py-3 font-normal leading-relaxed outline-none placeholder:text-ink/48 focus:border-[#006b6b] focus:ring-2 focus:ring-[#006b6b]/15" /></label>{error && <p role="alert" className="mt-3 text-sm font-medium text-red-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setNoteOpen(false)} className="min-h-11 rounded-lg border border-ink/15 px-5 text-sm font-medium">Cancelar</button><button type="button" onClick={() => void saveNote()} disabled={noteSaving || !note.trim()} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#006b6b] px-5 text-sm font-semibold text-white disabled:opacity-50">{noteSaving && <Loader2 className="h-4 w-4 animate-spin" />}Guardar nota</button></div></section></div>}
  </>;
}
