"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { CalendarCheck, Check, Copy, ExternalLink, Loader2, Mail } from "lucide-react";
import type { MeetingLink } from "@/lib/meeting-scheduler";

const days = [{v:1,l:"Lun"},{v:2,l:"Mar"},{v:3,l:"Mié"},{v:4,l:"Jue"},{v:5,l:"Vie"},{v:6,l:"Sáb"},{v:0,l:"Dom"}];
const slugify=(v:string)=>v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");

export function MeetingLinkManager({initial,agentName}:{initial:MeetingLink|null;agentName:string}) {
  const [form,setForm]=useState({slug:initial?.slug||slugify(agentName),title:initial?.title||`Reunión con ${agentName}`,location:initial?.location||"A definir",meetingModes:initial?.meetingModes||["in_person","google_meet"] as ("in_person"|"google_meet")[],durations:initial?.durations||[15,30,60],weekdays:initial?.weekdays||[1,2,3,4,5],startTime:initial?.startTime||"09:00",endTime:initial?.endTime||"18:00",slotInterval:initial?.slotInterval||15,active:initial?.active??true});
  const [saving,setSaving]=useState(false),[message,setMessage]=useState(""),[copied,setCopied]=useState(false);
  const base=typeof window!=="undefined"?window.location.origin:"https://barrerabrokers.com";
  const url=useMemo(()=>`${base}/reuniones/${form.slug}`,[base,form.slug]);
  const toggle=(key:"durations"|"weekdays",value:number)=>setForm(f=>({...f,[key]:f[key].includes(value)?f[key].filter(x=>x!==value):[...f[key],value].sort((a,b)=>a-b)}));
  const save=async()=>{setSaving(true);setMessage("");try{const r=await fetch("/api/crm/meeting-link",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage("Configuración guardada.");}catch(e){setMessage(e instanceof Error?e.message:"No se pudo guardar.");}finally{setSaving(false)}};
  const copy=async()=>{await navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),1800)};
  return <main className="mx-auto max-w-6xl space-y-6 pb-12">
    <header className="flex flex-col gap-4 border-b border-ink/10 pb-6 md:flex-row md:items-end md:justify-between">
      <div><p className="mb-2 text-sm font-medium text-[#0f766e]">Agenda online</p><h1 className="text-3xl font-semibold tracking-[-0.025em] text-ink">Link de reuniones</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-ink/65">Definí tu disponibilidad y compartí un enlace para que cada cliente reserve directamente en tu Google Calendar.</p></div>
      <Link href="/admin/crm/calendario" className="inline-flex items-center gap-2 text-sm font-semibold text-ink"><CalendarCheck className="h-4 w-4"/>Ver calendario</Link>
    </header>
    <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_360px]">
      <section className="space-y-7">
        <label className="block"><span className="text-sm font-semibold text-ink">Nombre de la reunión</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-2 w-full rounded-lg border border-ink/15 bg-white px-4 py-3 text-sm outline-none focus:border-[#0f766e]"/></label>
        <div><span className="text-sm font-semibold text-ink">Opciones que puede elegir el cliente</span><div className="mt-3 grid gap-3 sm:grid-cols-2">{[["in_person","Presencial","El cliente recibe la dirección."],["google_meet","Virtual por Google Meet","El enlace se genera automáticamente."]].map(([value,title,description])=>{const selected=form.meetingModes.includes(value as "in_person"|"google_meet");return <button key={value} type="button" aria-pressed={selected} onClick={()=>setForm({...form,meetingModes:selected?form.meetingModes.filter(item=>item!==value):[...form.meetingModes,value as "in_person"|"google_meet"]})} className={`relative rounded-lg border px-4 py-4 text-left text-sm transition-colors ${selected?"border-[#0f5b55] bg-[#0f5b55] text-white":"border-ink/20 bg-white text-ink hover:border-[#0f766e] hover:bg-[#f2fbf9]"}`}><strong className="flex items-center justify-between gap-3">{title}{selected&&<Check className="h-4 w-4 shrink-0"/>}</strong><span className={`mt-1 block ${selected?"text-white/78":"text-ink/62"}`}>{description}</span></button>})}</div></div>
        {form.meetingModes.includes("in_person")&&<label className="block"><span className="text-sm font-semibold text-ink">Dirección de la reunión presencial</span><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Ej.: Av. del Libertador 1234, CABA" className="mt-2 w-full rounded-lg border border-ink/15 bg-white px-4 py-3 text-sm outline-none focus:border-[#0f766e]"/></label>}
        <div><span className="text-sm font-semibold text-ink">Duraciones disponibles</span><div className="mt-3 flex flex-wrap gap-2">{[15,30,45,60].map(v=>{const selected=form.durations.includes(v);return <button key={v} type="button" aria-pressed={selected} onClick={()=>toggle("durations",v)} className={`rounded-full border px-4 py-2 text-sm font-medium transition-colors ${selected?"border-[#0f5b55] bg-[#0f5b55] text-white":"border-ink/20 bg-white text-ink hover:border-[#0f766e] hover:bg-[#f2fbf9]"}`}>{v===60?"1 hora":`${v} minutos`}</button>})}</div></div>
        <div><span className="text-sm font-semibold text-ink">Días disponibles</span><div className="mt-3 flex flex-wrap gap-2">{days.map(d=>{const selected=form.weekdays.includes(d.v);return <button key={d.v} type="button" aria-pressed={selected} onClick={()=>toggle("weekdays",d.v)} className={`h-10 min-w-12 rounded-lg border px-3 text-sm font-medium transition-colors ${selected?"border-[#0f5b55] bg-[#0f5b55] text-white":"border-ink/20 bg-white text-ink/65 hover:border-[#0f766e]"}`}>{d.l}</button>})}</div></div>
        <div className="grid gap-4 sm:grid-cols-3"><label className="text-sm font-semibold text-ink">Desde<input type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})} className="mt-2 w-full rounded-lg border border-ink/15 bg-white px-3 py-3 font-normal"/></label><label className="text-sm font-semibold text-ink">Hasta<input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})} className="mt-2 w-full rounded-lg border border-ink/15 bg-white px-3 py-3 font-normal"/></label><label className="text-sm font-semibold text-ink">Intervalos<select value={form.slotInterval} onChange={e=>setForm({...form,slotInterval:Number(e.target.value)})} className="mt-2 w-full rounded-lg border border-ink/15 bg-white px-3 py-3 font-normal"><option value={15}>15 minutos</option><option value={30}>30 minutos</option><option value={60}>1 hora</option></select></label></div>
        <label className="flex items-center gap-3"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})} className="h-4 w-4 accent-[#0f766e]"/><span className="text-sm font-medium text-ink">Enlace activo y disponible para reservas</span></label>
        <div className="flex items-center gap-4"><button onClick={save} disabled={saving||!form.durations.length||!form.weekdays.length||!form.meetingModes.length} className="inline-flex items-center gap-2 rounded-full bg-[#0f5b55] px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-[#0b4944] disabled:cursor-not-allowed disabled:bg-ink/20 disabled:text-ink/45">{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Guardar cambios</button>{message&&<span className="text-sm text-ink/65">{message}</span>}</div>
      </section>
      <aside className="h-fit rounded-xl bg-[#17384a] p-6 text-white lg:sticky lg:top-6"><p className="text-sm text-white/70">Tu enlace personal</p><p className="mt-3 break-all text-base font-semibold">{url}</p><div className="mt-6 grid gap-2"><button onClick={copy} className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-4 py-2.5 text-sm font-semibold text-[#17384a]">{copied?<Check className="h-4 w-4"/>:<Copy className="h-4 w-4"/>}{copied?"Copiado":"Copiar enlace"}</button><a href={url} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/30 px-4 py-2.5 text-sm font-semibold"><ExternalLink className="h-4 w-4"/>Vista del cliente</a><a href={`mailto:?subject=${encodeURIComponent("Agendemos una reunión")}&body=${encodeURIComponent(`Hola, podés elegir el día y horario que prefieras desde este enlace:\n\n${url}`)}`} className="inline-flex items-center justify-center gap-2 rounded-full border border-white/30 px-4 py-2.5 text-sm font-semibold"><Mail className="h-4 w-4"/>Enviar por mail</a></div><p className="mt-5 text-xs leading-5 text-white/60">Cuando el cliente confirma, recibe una invitación y la reunión aparece automáticamente en tu Google Calendar.</p></aside>
    </div>
  </main>;
}
